package com.example.modules.minio.dtos;

import com.example.base.utils.SwaggerExamples;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;
import lombok.Data;

@Builder
@Data
public class MinioFileResponse {

  @Schema(description = "The file name in MinIO", example = "folder/filename.ext")
  private final String fileName;

  @Schema(
    description = "The presigned URL for file entry generated by MinIO",
    example = SwaggerExamples.URL
  )
  private final String url;
}
